INSERT INTO TB_CATEGORY(name, created_AT) VALUES('BOOKS', NOW());
INSERT INTO TB_CATEGORY(name, created_AT) VALUES('ELETRONICS', NOW());
INSERT INTO TB_CATEGORY(name, created_AT) VALUES('COMPUTERS', NOW());